services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paye
    ports:
      - "5432:5432"
    volumes:
      - paye_db:/var/lib/postgresql/data

  api:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL='postgresql://neondb_owner:npg_qJOV2zh7XPKs@ep-falling-lab-aj2fzcjb-pooler.c-3.us-east-2.aws.neon.tech/payedb?sslmode=require&channel_binding=require'
      - JWT_SECRET=asfdsadfsafsfsfasfdsfsfsdfsdfsdfsdfsfsdfsdfsdfsd
      - ENCRYPTION_KEY=asfdsadfsafsfsfasfdsfsfsdfsdfsdfsdfsfsdfsdfsdfsd
    depends_on:
      - db

volumes:
  paye_db:
